### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by hortonelectric** [popmanhe/Node_Dice#1]
As of this writing, demo site ccroll is down. Can you please contact me ASAP to discuss some opportunities? hortonelectric@gmail.com

**Comment by popmanhe** [comment]
Hi,

    the host was expired. I did not renew it , so it is down.

    I am rewriting the front-end part in react.

    What opportunities are you talking about.


Neo

2017/3/11 20:43, hortonelectric wrote:

As of this writing, demo site ccroll is down. Can you please contact me ASAP to discuss some opportunities?

**Comment by hortonelectric** [comment]
Ah, react. Okay, yes we do seem to be on the same page in many areas. I
would like to introduce you to our team of game developers who are writing
games for BURSTcoin. I wonder if you're familiar with BURST, it's a
derivative of NXT that mines using "proof of capacity" IE extra HDD Space.

I am looking to expand my team which is building not only games but other
interesting applications in NodeJS and React.

I'm +639064325988 on Telegram

**Comment by popmanhe** [comment]
I'd like to hear more.  I don't use telegram. Please contact me via skype: neo_he

Neo

2017/3/11 22:09, hortonelectric wrote:
Ah, react. Okay, yes we do seem to be on the same page in many areas. I
would like to introduce you to our team of game developers who are writing
games for BURSTcoin. I wonder if you're familiar with BURST, it's a
derivative of NXT that mines using "proof of capacity" IE extra HDD Space.

I am looking to expand my team which is building not only games but other
interesting applications in NodeJS and React.

I'm +639064325988 on Telegram

**Comment by popmanhe** [comment]
The new demo site is up
