### ISSUE TITLE
Error on signup

### ISSUE THREAD

**Issue by redline187** [popmanhe/Node_Dice#2]
im getting error on signup 

dice_1   | 0|nodedice | error:  TypeError: Data must be a string or a buffer
dice_1   | 0|nodedice |     at Hash.update (crypto.js:74:16)
dice_1   | 0|nodedice |     at Function.CreateNewUser (/usr/nodedice/dist/nodeDiceServer.js:295:58)
dice_1   | 0|nodedice |     at Socket.socket.on (/usr/nodedice/dist/nodeDiceServer.js:1182:56)
dice_1   | 0|nodedice |     at emitOne (events.js:96:13)
dice_1   | 0|nodedice |     at Socket.emit (events.js:191:7)
dice_1   | 0|nodedice |     at /usr/nodedice/node_modules/socket.io/lib/socket.js:503:12
dice_1   | 0|nodedice |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
dice_1   | 0|nodedice |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by septk** [comment]
same error here

**Comment by popmanhe** [comment]
Sorry for the delay. I just fixed the issue. Please get the latest version and build it again. Let me know if any problems.
