### ISSUE TITLE
Problem when I build Docker

### ISSUE THREAD

**Issue by septk** [popmanhe/Node_Dice#3]
Hi, 

when I try to build with docker-compose build I have this error: 

Building raffle
ERROR: Cannot locate specified Dockerfile: Dockerfile

How can I resolve this?

thanks in advanced

**Comment by popmanhe** [comment]
raffle game is not ready yet.


On Jun 19, 2017 9:26 AM, septk <notifications@github.com> wrote:

Hi,

when I try to build with docker-compose build I have this error:

Building raffle
ERROR: Cannot locate specified Dockerfile: Dockerfile

How can I resolve this?

thanks in advanced

**Comment by popmanhe** [comment]
Sorry for the delay. I just fixed the issue. Please get the latest version and build it again. Let me know if any problems.

**Comment by septk** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) deposit and profile when I sign up.

Thanks for your support :)
