### ISSUE TITLE
Deposit and profile error

### ISSUE THREAD

**Issue by septk** [popmanhe/Node_Dice#4]
Failed to load resource: the server responded with a status of 404 (Not Found) deposit and profile when I sign up.

Thanks for your support :)

**Comment by popmanhe** [comment]
Please provide more info on this issue. Coin deposit and address won't work because you need a actual running btc client to do it. But it can be easily done by yourself. There is help class in the project. Modify that file and suit your needs.

**Comment by septk** [comment]
If you try your demo, you have same error than me. Try to sign up with a new user.!

@popmanhe thanks!

**Comment by popmanhe** [comment]
@septk 
Sorry for the late reply. I have been busy with other projects.  The issue is fixed now. You can try it again on the web site.
